site_name: djangorestframework-serializer-extensions
site_description: Extensions to DRY up Django Rest Framework serializers
repo_url: https://github.com/evenicoulddoit/django-rest-framework-serializer-extensions
site_dir: html
theme: readthedocs
extra_css:
  - css/extra.css
nav:
  - Home: 'index.md'
  - Overview: 'overview.md'
  - Installation: 'installation.md'
  - User Guide:
    - Serializers: 'usage-serializers.md'
    - Views: 'usage-views.md'
    - 'Automatic QuerySet optimization': 'auto-optimizations.md'
    - 'HashIds Support': 'usage-hashids.md'
    - 'API Reference': 'usage-api.md'
  - Examples: 'examples.md'
  - Contributing: 'contributing.md'
